### PR TITLE
Fix default bucket names to work with newer activesupport versions

### PR DESCRIPTION
**Pull request by SavithaK**
Potential fix for https://github.com/braintree/curator/issues/50

@pgr0ss

### CODE REVIEW

**Comment by SavithaK** [comment]
Confirmed that our app works again with this fix.

**Comment by pgr0ss** [comment]
Looks good. Thanks for the fix!

**Comment by SavithaK** [comment]
Thanks @pgr0ss ! Could you bump version please

**Comment by pgr0ss** [comment]
Done.

**Comment by SavithaK** [comment]
Thanks @pgr0ss - I pulled the new version 0.11.1 and it didn't contain my fix.. Any idea why?

**Comment by pgr0ss** [comment]
I must have messed it up. I just pushed 0.11.2. Can you try that one?

**Comment by SavithaK** [comment]
That worked! Much appreciated!

**Pull request merged**
